
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NumberService", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NumberService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     * @throws NumberServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumber", targetNamespace = "http://soap/", className = "soap.GetNumber")
    @ResponseWrapper(localName = "getNumberResponse", targetNamespace = "http://soap/", className = "soap.GetNumberResponse")
    @Action(input = "http://soap/NumberService/getNumberRequest", output = "http://soap/NumberService/getNumberResponse", fault = {
        @FaultAction(className = NumberServiceException.class, value = "http://soap/NumberService/getNumber/Fault/NumberServiceException")
    })
    public Integer getNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws NumberServiceException
    ;

}
